# Generated by Django 2.2.16 on 2022-12-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Статус текущего аккаунта - активирован или нет.', verbose_name='Активный/неактивный.'),
        ),
    ]
